// The catalog entries. Loaded on demand (see ./index.ts) so the JSON stays out of the main bundle.
// visiocafe.json is generated by scripts/scrape-visiocafe.py; vendors.json is curated by hand.
import type { CatalogPack } from '../lib/types';
import vendors from './vendors.json';
import visiocafe from './visiocafe.json';

interface VisioCafeVendor {
  vendor: string;
  page: string;
  packs: { name: string; description: string; collection: string; url: string; sizeBytes: number | null; updated: string }[];
}

interface VendorEntry {
  vendor: string;
  name: string;
  description: string;
  url: string;
  homepage: string;
  sizeBytes?: number | null;
  cors?: boolean;
}

const slug = (s: string) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

export const catalog: CatalogPack[] = [
  ...(vendors as VendorEntry[]).map((v) => ({
    id: `vendor-${slug(v.vendor)}-${slug(v.name)}`,
    vendor: v.vendor,
    name: v.name,
    description: v.description,
    url: v.url,
    homepage: v.homepage,
    sizeBytes: v.sizeBytes ?? null,
    cors: v.cors ?? false,
    source: 'vendor' as const,
  })),
  ...(visiocafe as VisioCafeVendor[]).flatMap((v) =>
    v.packs.map((p) => ({
      id: `visiocafe-${slug(v.vendor)}-${slug(p.name)}`,
      vendor: v.vendor,
      name: p.name.replace(/[-_]+/g, ' '),
      description: p.description,
      collection: p.collection || undefined,
      url: p.url,
      homepage: v.page,
      sizeBytes: p.sizeBytes,
      updated: p.updated || undefined,
      source: 'visiocafe' as const,
    })),
  ),
];
